"""user account and registration module

Revision ID: 0001
Revises: 
Create Date: 2026-10-08 18:34:59.221734

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_audit_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('target_user_id', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('changed_fields', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_auth_audit_target', 'auth_audit_events', ['target_user_id', 'created_at'], unique=False)
    op.create_table('auth_rate_limits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bucket_key', sa.String(length=255), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bucket_key', 'window_start', name='uq_rate_bucket')
    )
    op.create_table('email_outbox',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth_transactions',
    sa.Column('state_digest', sa.String(length=128), nullable=False),
    sa.Column('nonce', sa.String(length=128), nullable=False),
    sa.Column('code_verifier', sa.String(length=128), nullable=False),
    sa.Column('return_to', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('state_digest')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('username_normalized', sa.String(length=64), nullable=True),
    sa.Column('student_id', sa.String(length=64), nullable=True),
    sa.Column('college', sa.String(length=120), nullable=True),
    sa.Column('requested_identity', sa.String(length=16), nullable=True),
    sa.Column('roles', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False),
    sa.Column('account_status', sa.String(length=16), nullable=False),
    sa.Column('disabled_reason', sa.Text(), nullable=True),
    sa.Column('disabled_at', sa.DateTime(), nullable=True),
    sa.Column('preferred_locale', sa.String(length=16), nullable=True),
    sa.Column('auth_version', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username_normalized')
    )
    op.create_table('academic_identity_checks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('checked_fields', sa.JSON(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('evidence_ref', sa.String(length=255), nullable=True),
    sa.Column('checked_by', sa.String(length=64), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_academic_checks_user', 'academic_identity_checks', ['user_id'], unique=False)
    op.create_table('auth_identities',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('issuer', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('google_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_authenticated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'issuer', 'subject', name='uq_auth_identity_key')
    )
    op.create_index('ix_auth_identities_user', 'auth_identities', ['user_id'], unique=False)
    op.create_table('email_challenges',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('email_normalized', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('code_hmac', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(), nullable=True),
    sa.Column('send_status', sa.String(length=16), nullable=False),
    sa.Column('resend_available_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_email_challenges_user_purpose', 'email_challenges', ['user_id', 'purpose'], unique=False)
    op.create_index('uq_email_challenge_active', 'email_challenges', ['user_id', 'purpose'], unique=True, postgresql_where=sa.text('consumed_at IS NULL AND invalidated_at IS NULL'))
    op.create_table('school_email_bindings',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('school_email', sa.String(length=255), nullable=True),
    sa.Column('school_email_normalized', sa.String(length=255), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verification_method', sa.String(length=32), nullable=True),
    sa.Column('pending_school_email', sa.String(length=255), nullable=True),
    sa.Column('pending_school_email_normalized', sa.String(length=255), nullable=True),
    sa.Column('pending_requested_at', sa.DateTime(), nullable=True),
    sa.Column('change_authorized_until', sa.DateTime(), nullable=True),
    sa.Column('change_authorized_target', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('school_email_normalized', name='uq_school_email_verified')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('token_digest', sa.String(length=128), nullable=False),
    sa.Column('csrf_token', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('auth_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('absolute_expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoke_reason', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_digest')
    )
    op.create_index('ix_sessions_user', 'sessions', ['user_id'], unique=False)
    op.create_table('teacher_applications',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('application_version', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reviewer_id', sa.String(length=64), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_teacher_applications_user', 'teacher_applications', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_teacher_applications_user', table_name='teacher_applications')
    op.drop_table('teacher_applications')
    op.drop_index('ix_sessions_user', table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('school_email_bindings')
    op.drop_index('uq_email_challenge_active', table_name='email_challenges', postgresql_where=sa.text('consumed_at IS NULL AND invalidated_at IS NULL'))
    op.drop_index('ix_email_challenges_user_purpose', table_name='email_challenges')
    op.drop_table('email_challenges')
    op.drop_index('ix_auth_identities_user', table_name='auth_identities')
    op.drop_table('auth_identities')
    op.drop_index('ix_academic_checks_user', table_name='academic_identity_checks')
    op.drop_table('academic_identity_checks')
    op.drop_table('users')
    op.drop_table('oauth_transactions')
    op.drop_table('email_outbox')
    op.drop_table('auth_rate_limits')
    op.drop_index('ix_auth_audit_target', table_name='auth_audit_events')
    op.drop_table('auth_audit_events')
    # ### end Alembic commands ###
