"""pre-registration, login email verification, auth method

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-09 00:11:23.835717

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pre_registration_requests',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('email_normalized', sa.String(length=255), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=True),
    sa.Column('browser_token_digest', sa.String(length=128), nullable=False),
    sa.Column('code_hmac', sa.String(length=128), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('send_status', sa.String(length=16), nullable=False),
    sa.Column('resend_available_at', sa.DateTime(), nullable=True),
    sa.Column('code_consumed_at', sa.DateTime(), nullable=True),
    sa.Column('creation_grant_digest', sa.String(length=128), nullable=True),
    sa.Column('creation_grant_expires_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('result_user_id', sa.String(length=64), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pre_registration_email', 'pre_registration_requests', ['email_normalized'], unique=False)
    op.create_index('uq_pre_registration_grant', 'pre_registration_requests', ['creation_grant_digest'], unique=True)
    op.add_column('email_challenges', sa.Column('credential_version', sa.Integer(), nullable=True))
    op.add_column('password_credentials', sa.Column('login_email_verified_at', sa.DateTime(), nullable=True))
    op.add_column('password_credentials', sa.Column('verification_evidence_ref', sa.String(length=255), nullable=True))
    op.add_column('password_credentials', sa.Column('credential_version', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('sessions', sa.Column('auth_method', sa.String(length=16), nullable=True))
    op.add_column('sessions', sa.Column('credential_version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'credential_version')
    op.drop_column('sessions', 'auth_method')
    op.drop_column('password_credentials', 'credential_version')
    op.drop_column('password_credentials', 'verification_evidence_ref')
    op.drop_column('password_credentials', 'login_email_verified_at')
    op.drop_column('email_challenges', 'credential_version')
    op.drop_index('uq_pre_registration_grant', table_name='pre_registration_requests')
    op.drop_index('ix_pre_registration_email', table_name='pre_registration_requests')
    op.drop_table('pre_registration_requests')
    # ### end Alembic commands ###
